# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
permalink:           /blog/:categories/:year/:month/:day/:title.html

# Setup
title:               Rahil Shah
tagline:             'Upcoming Data Engineer at Northeastern.'

# description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
description:         'The digital portfolio of Rahil Shah. Data Engineer. Data Analyst. BI Analyst.'
url:                 http://rahilshah10.github.io
baseurl:             ''
blogurl:             '/blog'
paginate:            5

# Pagination
paginate_path:       'blog/page:num/'

# About/contact
author:
  name:              Rahil Shah
  url:               http://rahilshah10.github.io
  email:             shah.rah@husky.neu.edu

# Custom vars
version:             1.0.0

#Gems
gems:
  - jekyll-paginate
  - jekyll-assets
  - jekyll-seo-tag

# Compress.html
compress_html:
  comments: ["<!-- ", " -->"]


# jekyll-assets
assets:
  compress:
    js: true
    css: true

  assets:
    - "*.png"
    - "*.jpeg"
    - "*.jpg"

  sources:
    - public/project-images/card-headers
